### ISSUE TITLE
User Friendly Error Messages

### ISSUE THREAD

**Issue by brandonlou** [Team4159/birds#114]
"Cannot read property 'replace' of undefined"

**Comment by eliaslfox** [comment]
LOL, what form and what were you doing?

**Comment by eliaslfox** [comment]
@brandonlou what were you doing?

**Comment by brandonlou** [comment]
@eliaslfox I clicked the register button without having completed any of the input fields

**Comment by eliaslfox** [comment]
@brandonlou well, that would do it

**Comment by eliaslfox** [comment]
This was fixed in another pr

**Comment by eliaslfox** [comment]
This was fixed in another pr
