### ISSUE TITLE
Register Form

### ISSUE THREAD

**Issue by brandonlou** [Team4159/birds#63]
- [ ] Check if email is valid
- [ ] Have user retype password (front end)

**Comment by eliaslfox** [comment]
How should we check if the email is valid? I could write some regexp, the rules are hella complicated, see below. As a result I think that we should instead send a verification email to the user upon registration.

**Comment by eliaslfox** [comment]
Look at this crap [https://en.wikipedia.org/wiki/Email_address](https://en.wikipedia.org/wiki/Email_address)
